customCommands:
  - key: G
    contex: status
    description: "Set Git config user name and email"
    commandMenu:
      - key: g
        description: codazendev
        command: git config user.name "Jeremy King" && git config user.email codazendev@gmail.com
      - key: h
        description: jgkingdev
        command: git config user.name "Jeremy King" && git config user.email jeremykingdev@gmail.com
