#!/bin/sh
# Set up my shell aliases

# Colorize aliases
alias ls='ls --color=auto'
alias grep='grep --color=auto'

# Shorthand aliases
alias sudo='sudo '
alias hx='helix'
alias g='git'
alias gg='lazygit'

# Screenshot aliases
alias scopy='grim -g "$(slurp)" - | wl-copy'
alias sshot='grim -g "$(slurp)"'
