#!/bin/sh
# $XDG_CONFIG_HOME/shell/alias
# Use this file to set interactive shell-specific configurations. Aliases are the primary thing that goes here. Anything specific to a certain shell (bash, zsh) stays in the respective file that sources this one.

# Colorize aliases
alias ls='ls --color=auto'
alias grep='grep --color=auto'

# Shorthand aliases
alias sudo='sudo '
alias hx='helix'
alias g='git'
alias gg='lazygit'

# Screenshot aliases
alias scopy='grim -g "$(slurp)" - | wl-copy'
alias sshot='grim -g "$(slurp)"'

