#!/bin/zsh
# Used for executing user's commands at start, will be read when starting as a login shell.
# Typically used to autostart graphical sessions and to set session-wide environment variables.

# Register ssh keys with keychain so github works
eval $(keychain --eval --quiet ~/.ssh/id_github_codazendev)
eval $(keychain --eval --quiet ~/.ssh/id_github_jgkingdev)