#!/bin/zsh
# Set up my shell aliases

# Colorized aliases
alias ls='ls --color=auto'
alias grep='grep --color=auto'

# Shorthand aliases
alias hx='helix'

# Screenshot aliases
alias scopy='grim -g "$(slurp)" - | wl-copy'
alias sshot='grim -g "$(slurp)"'

# Distraction alias for rbonsai
alias distract='rbonsai -S'

# Godot alias for MQP
alias misfits='gdvm run 4.5'
